package skill_test

// pastSkills is SKILL.md as embedded at each commit that changed it before
// the current one, inlined verbatim.
var pastSkills = []struct {
	commit string
	sha256 string
	body   string
}{
	{commit: "bc94d31", sha256: "18209f1d521d0bb0ef74de150c145ffd8151eb448d58a807c16e0a68c1a849ef", body: "`description:` claims the intents — \"what was I doing\", \"resume\", \"why did we\", \"backstory\", \"history\", \"last session\".\nif a SessionStart block is present, do not re-fetch; else call `recall` for this project once.\nbefore changing a file whose recall shows a declared decision, read it.\nwhen you choose between alternatives, `note decision` in one line — no ceremony.\nclaim \"done\" only with `note outcome` pointing at a `timeline` event id; a claim without evidence is recorded as a claim.\nend with `note handoff`: what is true now, what is next, what not to do.\ninferred records are hints; declared records are claims; the timeline is fact.\nnever put a secret in a note.\n"},
	{commit: "47c25fb", sha256: "c6003812bf66a715cbdee95c5c41a959803219926bd30f9271411a18f8368822", body: "`description:` claims the intents — \"what was I doing\", \"resume\", \"why did we\", \"backstory\", \"history\", \"last session\".\nif a SessionStart block is present, do not re-fetch; else call `recall` for this project once.\nbefore changing a file whose recall shows a declared decision, read it.\nwhen you choose between alternatives, `note decision` in one line — no ceremony.\nclaim \"done\" only with `note outcome` pointing at a `timeline` event id; a claim without evidence is recorded as a claim.\nend with `note handoff`: what is true now, what is next, what not to do — set `supersedes` to the Resume slot's id when it showed one.\ninferred records are hints; declared records are claims; the timeline is fact.\nnever put a secret in a note.\n"},
	{commit: "f0616db", sha256: "0f626aa1b0172683d985881cf9d93e424f7aa7c57f23f54875c8af90cb157abd", body: "`description:` claims the intents — \"what was I doing\", \"resume\", \"why did we\", \"backstory\", \"history\", \"last session\".\nif a SessionStart block is present, do not re-fetch; else call `recall` for this project once; if the Resume line carries a possibly-stale marker, verify it before acting and `confirm affirm` it if still true.\nbefore changing a file whose recall shows a declared decision, read it.\nwhen you choose between alternatives, `note decision` in one line — no ceremony.\nclaim \"done\" only with `note outcome` pointing at a `timeline` event id; a claim without evidence is recorded as a claim.\nend with `note handoff`: what is true now, what is next, what not to do — set `supersedes` to the Resume slot's id when it showed one.\ninferred records are hints; declared records are claims; the timeline is fact.\nnever put a secret in a note.\n"},
	{commit: "e887d71", sha256: "1d1016ae20d05095fd16712e2fa7be5c8a14b5f2c96685e55288de740ffa8a35", body: "`description:` claims the intents — \"what was I doing\", \"resume\", \"why did we\", \"backstory\", \"history\", \"last session\".\nif a SessionStart block is present, do not re-fetch; else call `recall` for this project once; if the Resume line carries a possibly-stale marker, verify it before acting and `confirm affirm` it if still true.\nbefore changing a file whose recall shows a declared decision, read it.\nwhen you choose between alternatives, `note decision` in one line — no ceremony.\nclaim \"done\" only with `note outcome` pointing at a `timeline` event id; a claim without evidence is recorded as a claim.\nend with `note handoff`: what is true now, what is next, what not to do — set `supersedes` to the Resume slot's id when it showed one; whenever any record replaces or corrects an earlier one, set `supersedes` to its id (or `confirm supersede`).\ninferred records are hints; declared records are claims; the timeline is fact.\nnever put a secret in a note.\n"},
	{commit: "462e93f", sha256: "6d39ea0375361d25aa77430aabb8cf25910818c3f82465c2ff4fa550084acaed", body: "`description:` claims the intents — \"what was I doing\", \"resume\", \"why did we\", \"backstory\", \"history\", \"last session\".\nif a SessionStart block is present, do not re-fetch; else call `recall` for this project once; if the Resume line carries a possibly-stale marker, verify it before acting and `confirm affirm` it if still true.\nbefore changing a file whose recall shows a declared decision, read it.\nwhen you choose between alternatives, `note decision` in one line — no ceremony.\nclaim \"done\" only with `note outcome` pointing at a `timeline` event id; a claim without evidence is recorded as a claim.\nend with `note handoff`: what is true now, what is next, what not to do. Put the single next step in the handoff's optional `next` (one line, at most 200 characters; handoff only) so the panel can show it. Set `supersedes` to the Resume slot's id when it showed one; whenever any record replaces or corrects an earlier one, set `supersedes` to its id (or `confirm supersede`).\ninferred records are hints; declared records are claims; the timeline is fact.\nnever put a secret in a note.\n"},
	{commit: "de430a0", sha256: "47d86ad1e62945d890f710016e46e694529249961cd23320d251a2cc2b03389d", body: "---\nname: backstory\ndescription: \"Backstory is the project's memory across sessions. Use when the user asks 'what was I doing', 'resume', 'why did we', 'backstory', 'history', or 'last session', and to record decisions, outcomes and handoffs with the backstory recall/note/timeline/confirm tools.\"\n---\nif a SessionStart block is present, do not re-fetch; else call `recall` for this project once; if the Resume line carries a possibly-stale marker, verify it before acting and `confirm affirm` it if still true.\nbefore changing a file whose recall shows a declared decision, read it.\nwhen you choose between alternatives, `note decision` in one line — no ceremony.\nclaim \"done\" only with `note outcome` pointing at a `timeline` event id; a claim without evidence is recorded as a claim.\nend with `note handoff`: what is true now, what is next, what not to do. Put the single next step in the handoff's optional `next` (one line, at most 200 characters; handoff only) so the panel can show it. Set `supersedes` to the Resume slot's id when it showed one; whenever any record replaces or corrects an earlier one, set `supersedes` to its id (or `confirm supersede`).\ninferred records are hints; declared records are claims; the timeline is fact.\nnever put a secret in a note.\n"},
	{commit: "4b17457", sha256: "6a4ef07351a45104107b930044304cccaeb9cfa2ae5e4c57204f293291911419", body: "---\nname: backstory\ndescription: \"Backstory is the project's memory across sessions. Use when the user asks 'what was I doing', 'resume', 'why did we', 'backstory', 'history', or 'last session', and to record decisions, outcomes and handoffs with the backstory recall/note/timeline/confirm tools.\"\n---\nif a SessionStart block is present, do not re-fetch; else call `recall` for this project once; if the Resume line carries a possibly-stale marker, verify it before acting and `confirm affirm` it if still true.\nbefore changing a file whose recall shows a declared decision, read it.\nwhen you choose between alternatives, `note decision` in one line — no ceremony.\nclaim \"done\" only with `note outcome` pointing at a `timeline` event id; a claim without evidence is recorded as a claim.\nend with `note handoff`: what is true now, what is next, what still must not be done. Do not carry forward instructions that applied only to the current session (\"don't start X now\" when X is the next step); `next` is an action the next session can start, with a precondition only if it is real and unmet. Put the single next step in the handoff's optional `next` (one line, at most 200 characters; handoff only) so the panel can show it. Set `supersedes` to the Resume slot's id when it showed one; whenever any record replaces or corrects an earlier one, set `supersedes` to its id (or `confirm supersede`).\ninferred records are hints; declared records are claims; the timeline is fact.\nnever put a secret in a note.\n"},
}
