// Backstory's Pi extension, written by `backstory install pi` to
// ~/.pi/agent/extensions/backstory/index.ts. Pi has no built-in MCP, so this
// extension is the bridge:
//   - session_start:         spawns `backstory mcp` (stdio JSON-RPC) once per
//                            session and registers the tools it lists.
//   - before_agent_start:    injects the warm block ONCE per session (an
//                            injection, not a tool call: small local models
//                            call tools unreliably).
//   - tool_execution_end:    forwards the finished tool call to
//                            `backstory hook post-tool-use --harness pi`,
//                            fire-and-forget; a failing hook never reaches Pi.
// Generated by backstory; `backstory install pi --remove` deletes it.
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";
import { spawn } from "node:child_process";
import type { ChildProcess } from "node:child_process";

// Tunables. BACKSTORY_BIN lets a non-PATH install (or a test) name the binary.
const BACKSTORY_BIN = process.env.BACKSTORY_BIN || "backstory";
const MCP_PROTOCOL_VERSION = "2025-06-18";
const MCP_REQUEST_TIMEOUT_MS = 15_000;
const WARM_BLOCK_TIMEOUT_MS = 10_000;
const HOOK_TIMEOUT_MS = 10_000;
const CUSTOM_MESSAGE_TYPE = "backstory";

// Pi reports lowercase tool names; the hook keys off Claude's spelling.
const HOOK_TOOL_NAMES: Record<string, string> = {
  bash: "Bash",
  read: "Read",
  edit: "Edit",
  write: "Write",
};

interface McpTool {
  name: string;
  description?: string;
  inputSchema?: Record<string, unknown>;
}

interface Pending {
  resolve: (value: any) => void;
  reject: (err: Error) => void;
  timer: ReturnType<typeof setTimeout>;
}

// McpClient is a minimal newline-delimited JSON-RPC client over the stdio of
// one `backstory mcp` child.
class McpClient {
  private child: ChildProcess;
  private nextId = 1;
  private pending = new Map<number, Pending>();
  private buf = "";
  private dead: Error | null = null;

  constructor() {
    this.child = spawn(BACKSTORY_BIN, ["mcp"], { stdio: ["pipe", "pipe", "ignore"] });
    this.child.stdout!.setEncoding("utf8");
    this.child.stdout!.on("data", (chunk: string) => this.onData(chunk));
    this.child.stdin!.on("error", () => {});
    this.child.on("error", (err) => this.fail(err));
    this.child.on("exit", () => this.fail(new Error("backstory mcp exited")));
  }

  private fail(err: Error): void {
    if (this.dead) return;
    this.dead = err;
    for (const p of this.pending.values()) {
      clearTimeout(p.timer);
      p.reject(err);
    }
    this.pending.clear();
  }

  private onData(chunk: string): void {
    this.buf += chunk;
    let nl: number;
    while ((nl = this.buf.indexOf("\n")) >= 0) {
      const line = this.buf.slice(0, nl).trim();
      this.buf = this.buf.slice(nl + 1);
      if (!line) continue;
      let msg: any;
      try {
        msg = JSON.parse(line);
      } catch {
        continue;
      }
      const p = typeof msg.id === "number" ? this.pending.get(msg.id) : undefined;
      if (!p) continue;
      this.pending.delete(msg.id);
      clearTimeout(p.timer);
      if (msg.error) p.reject(new Error(msg.error.message || "mcp error"));
      else p.resolve(msg.result);
    }
  }

  request(method: string, params?: unknown): Promise<any> {
    if (this.dead) return Promise.reject(this.dead);
    const id = this.nextId++;
    return new Promise((resolve, reject) => {
      const timer = setTimeout(() => {
        this.pending.delete(id);
        reject(new Error(`mcp ${method} timed out`));
      }, MCP_REQUEST_TIMEOUT_MS);
      this.pending.set(id, { resolve, reject, timer });
      this.child.stdin!.write(JSON.stringify({ jsonrpc: "2.0", id, method, params }) + "\n");
    });
  }

  notify(method: string): void {
    if (this.dead) return;
    this.child.stdin!.write(JSON.stringify({ jsonrpc: "2.0", method }) + "\n");
  }

  async initialize(): Promise<void> {
    await this.request("initialize", {
      protocolVersion: MCP_PROTOCOL_VERSION,
      capabilities: {},
      clientInfo: { name: "backstory-pi-extension", version: "1" },
    });
    this.notify("notifications/initialized");
  }

  close(): void {
    this.fail(new Error("closed"));
    this.child.kill();
  }
}

// runBackstory runs `backstory <args>` with stdin, returning stdout. It
// resolves (never rejects) with "" on any failure or timeout.
function runBackstory(args: string[], stdin: string, timeoutMs: number): Promise<string> {
  return new Promise((resolve) => {
    let out = "";
    let settled = false;
    const done = (value: string) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve(value);
    };
    let child: ChildProcess;
    try {
      child = spawn(BACKSTORY_BIN, args, { stdio: ["pipe", "pipe", "ignore"] });
    } catch {
      resolve("");
      return;
    }
    const timer = setTimeout(() => {
      child.kill();
      done("");
    }, timeoutMs);
    child.stdout!.setEncoding("utf8");
    child.stdout!.on("data", (c: string) => (out += c));
    child.stdin!.on("error", () => {});
    child.on("error", () => done(""));
    child.on("close", (code) => done(code === 0 ? out : ""));
    child.stdin!.end(stdin);
  });
}

function sessionIdOf(ctx: any): string {
  try {
    return String(ctx?.sessionManager?.getSessionId?.() ?? "");
  } catch {
    return "";
  }
}

function resultText(result: any): string {
  const content = result?.content;
  if (!Array.isArray(content)) return typeof result === "string" ? result : "";
  return content
    .filter((c: any) => c && c.type === "text" && typeof c.text === "string")
    .map((c: any) => c.text)
    .join("\n");
}

// hookPayload maps one finished Pi tool call onto the JSON shape
// `backstory hook post-tool-use` reads. No exit_code is sent: Pi does not
// report one, and the hook must never be told a 0 nobody observed.
function hookPayload(event: any, args: any, sessionId: string): string {
  const name = String(event.toolName ?? "");
  const input: Record<string, unknown> = { ...(args ?? {}) };
  if (typeof input.path === "string" && input.file_path === undefined) input.file_path = input.path;
  const text = resultText(event.result);
  return JSON.stringify({
    session_id: sessionId,
    hook_event_name: "tool_execution_end",
    tool_name: HOOK_TOOL_NAMES[name] ?? name,
    tool_use_id: event.toolCallId,
    tool_input: input,
    tool_response: name === "bash" ? { stdout: text } : { text },
    is_error: Boolean(event.isError),
  });
}

export default function (pi: ExtensionAPI) {
  let client: McpClient | null = null;
  let injected = false;
  const registered = new Set<string>();
  const toolArgs = new Map<string, any>();

  const registerTools = (mcp: McpClient, tools: McpTool[]) => {
    for (const tool of tools) {
      if (registered.has(tool.name)) continue;
      registered.add(tool.name);
      pi.registerTool({
        name: tool.name,
        label: tool.name,
        description: tool.description ?? "",
        parameters: tool.inputSchema ?? { type: "object", properties: {} },
        async execute(_toolCallId: string, params: any) {
          const live = client ?? mcp;
          try {
            const res = await live.request("tools/call", { name: tool.name, arguments: params ?? {} });
            const text = resultText(res) || JSON.stringify(res ?? {});
            return { content: [{ type: "text", text }], details: {}, isError: Boolean(res?.isError) };
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            return { content: [{ type: "text", text: `backstory: ${msg}` }], details: {}, isError: true };
          }
        },
      } as any);
    }
  };

  const startSession = async () => {
    injected = false;
    client?.close();
    client = null;
    try {
      const mcp = new McpClient();
      client = mcp;
      await mcp.initialize();
      const listed = await mcp.request("tools/list", {});
      registerTools(mcp, listed?.tools ?? []);
    } catch {
      // No backstory on this machine, or it is misbehaving: Pi runs without it.
    }
  };

  pi.on("session_start", async () => {
    await startSession();
  });

  pi.on("session_shutdown", async () => {
    client?.close();
    client = null;
    toolArgs.clear();
  });

  pi.on("before_agent_start", async (_event: any, ctx: any) => {
    if (injected) return;
    injected = true;
    const block = (
      await runBackstory(["hook", "session-start"], JSON.stringify({ session_id: sessionIdOf(ctx) }), WARM_BLOCK_TIMEOUT_MS)
    ).trim();
    if (!block) {
      injected = false; // nothing to inject yet; try again next turn
      return;
    }
    return { message: { customType: CUSTOM_MESSAGE_TYPE, content: block, display: false } };
  });

  pi.on("tool_execution_start", (event: any) => {
    if (event?.toolCallId) toolArgs.set(event.toolCallId, event.args);
  });

  pi.on("tool_execution_end", (event: any, ctx: any) => {
    try {
      const args = toolArgs.get(event?.toolCallId);
      toolArgs.delete(event?.toolCallId);
      const payload = hookPayload(event, args, sessionIdOf(ctx));
      void runBackstory(["hook", "post-tool-use", "--harness", "pi"], payload, HOOK_TIMEOUT_MS).catch(() => {});
    } catch {
      // A hook problem must never reach Pi.
    }
  });
}
